name = "falco-investments"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

# Production environment configuration
[env.production.vars]
ADMIN_EMAIL = "kontakt@przyjaznedomy.com"
COMPANY_NAME = "FALCO INVESTMENTS SP.ZO.O."
COMPANY_PHONE = "668374950"
WHATSAPP_NUMBER = "48668374950"
ENVIRONMENT = "production"
NODE_ENV = "production"

# KV Namespace for reservations - production
[[env.production.kv_namespaces]]
binding = "RESERVATIONS"
id = "WILL_BE_GENERATED"
preview_id = "WILL_BE_GENERATED_PREVIEW"

# Preview environment configuration
[env.preview.vars]
ADMIN_EMAIL = "kontakt@przyjaznedomy.com"
COMPANY_NAME = "FALCO INVESTMENTS SP.ZO.O."
COMPANY_PHONE = "668374950"
WHATSAPP_NUMBER = "48668374950"
ENVIRONMENT = "preview"
NODE_ENV = "preview"

# KV Namespace for reservations - preview
[[env.preview.kv_namespaces]]
binding = "RESERVATIONS"
id = "WILL_BE_GENERATED"
preview_id = "WILL_BE_GENERATED_PREVIEW"
