name = "falco-investments"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

# Environment variables
[vars]
ADMIN_EMAIL = "kontakt@przyjaznedomy.com"
COMPANY_NAME = "FALCO INVESTMENTS SP.ZO.O."
COMPANY_PHONE = "668374950"
WHATSAPP_NUMBER = "48668374950"
ENVIRONMENT = "production"
NODE_ENV = "production"

# KV Namespaces
[[kv_namespaces]]
binding = "RESERVATIONS"
id = "bdecc21b8a9d49e3a57c6e2df8fe8c04"

[[kv_namespaces]]
binding = "SESSION"
id = "5e32a704dde745efbb6e9be058474a59"

[[kv_namespaces]]
binding = "NEWSLETTER"
id = "32647a4c309b47b489f127d557d1e0a4"
